name: Go
on: [push]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go_version: [1.11, 1.12, 1.13, 1.14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Create log folder
        run: mkdir /home/runner/.scope-results

      - name: Test
        run: go test -v -race -covermode=atomic ./...
        env:
          SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
          SCOPE_LOGGER_ROOT: /home/runner/.scope-results
          SCOPE_DEBUG: true
          SCOPE_RUNNER_ENABLED: true
          SCOPE_RUNNER_EXCLUDE_BRANCHES: master
          SCOPE_TESTING_FAIL_RETRIES: 3
          SCOPE_TESTING_PANIC_AS_FAIL: true

      - name: Go check benchmark
        run: go test ./instrumentation/gocheck -gocheck.b -v
        if: matrix.os == 'ubuntu-latest'
        env:
          SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
          SCOPE_LOGGER_ROOT: /home/runner/.scope-results
          SCOPE_DEBUG: true

      - name: Upload Scope logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Scope for Go logs
          path: /home/runner/.scope-results

  fossa:
    name: FOSSA
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: FOSSA check
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          fossa analyze
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
